### ISSUE TITLE
Greedy Algo - Checking patterns shortest to longest

### ISSUE THREAD

**Issue by nhatbui** [nhatbui/libhrc#5]
Proposed by @ehsankia

In greedy algo, check shortest to longest patterns.

**Comment by EhsanKia** [comment]
To continue the discussion in the other thread...

You seemed to imply in your other message that you're working at the character level, which would be silly. But I see that you're using a space delimiter and working with words in your demo. That combined with the fact that Twitch messages are at most 500 characters greatly caps the complexity of the problem.

**Comment by nhatbui** [comment]
You're absolutely right about char level and word level and I apologize. I tokenize and do pattern finding at the word level. When explaining the algorithm, I discuss it at the character because that's usually how it's taught.

Eventually I want to move to an ideal solution as opposed to this heuristic approach. One of the first steps would be to find a ILP silver in JS...

N

**Comment by nhatbui** [comment]
Checking pattern length is the wrong approach.
Had we reverse it, the following example would be inaccurately compressed:

Test: 'a b c c a b c c'
Expected: '<a b c c x2>'
Outcome: 'a b <c x2> a b <c x2>'

Library has been updated to compute a metric referred to as _savings_. Library will compress patterns with the most potential _savings_.

_savings_ = _numOfTokens_ * (_numRepeats_ - 1)
